guru:
  jms:
    username: JMS USER
    password: somepass
    url: SomeURL
  username: Some User
  password: Some Normal Password
  dburl: Some Another Url

---  # FILE SEPARATOR!
spring:
  profiles: de

guru:
  jms:
    username: GERMAN JMS USER
    password: GERMAN JMS somepass
    url: GERMAN URL